### PR TITLE
Removed various no longer needed dependencies

### PR DESCRIPTION
**Pull request by pfeigl**
Various (mostly System.*) dependencies have been removed.
This is due to the fact, that they were needed by IdentityModel in previous (2.x) versions but are no longer need in the current 3.x versions.

This makes the dependency footprint alot smaller

### CODE REVIEW

**Comment by pfeigl** [comment]
I also pushed some relevant dependencies to their latest versions

**Comment by pfeigl** [comment]
Build is failing because it can't find `System.Net.Http` because it seems to use msbuild12, which is really old.

Is there any chance to build the project on AppVeyor with a more current version?

**Comment by pfeigl** [comment]
I also updated to IdentityModel4 now

**Comment by Rzpeg** [comment]
Hey, 
I will take a look later and then will merge it

**Pull request merged**
